### PR TITLE
Merge upstream 

### PR DESCRIPTION
**Pull request by rinatkhaziev**
An attempt on upstream merge 🤞

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
This has a few issues:

Looks like some naming convention changed from v3.5 to v3.6

```
3453-production 09:22:55 WARN ==> compose is not a supported service type.
3453-production 09:22:55 VERBOSE ==> building compose service devtools
Error: Cannot read property 'builder' of undefined
```

in `lib/factory.js`

`this.registry` contains the services with names prefixed, e.g. `_compose`. But we pass `compose` somehow. 

Bypassed via a hack:

```javascript
  get(name = '') {
    console.log("name", name, this.registry);
    if (name === 'compose') {
      name = '_compose';
    }

    return (!_.isEmpty(name)) ? _.find(this.registry, {name}).builder : this.registry;
  };
```


type `memcached:custom` is not supported. - commented out and locked the .lando.yml

```yaml
  memcached:
    type: memcached:custom
    overrides:
      image: memcached:1.6-alpine3.16
      command: docker-entrypoint.sh memcached
```

I gave up at this:


```
ERROR: The Compose file '/var/folders/g7/jxsxxw755db3hcqh6ynkbk3m0000gn/T/lando/compose/3453production/devtools-0.yml' is invalid because:
'registry' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```

```
at /var/folders/g7/jxsxxw755db3hcqh6ynkbk3m0000gn/T/lando/compose/3453production/devtools-0.yml
registry:
  - name: _compose
  - name: _recipe
  - name: _lando
  - name: _appserver
  - name: _service
  - name: _landoutil
  - name: _webserver
  - name: _drupaly
  - name: _lamp
  - name: _casetup
  - name: _proxy
  - name: _init
  - name: _mounter
```

**Comment by sjinks** [comment]
Pretty interesting thing is that the failed tests pass locally :-/

**Comment by sjinks** [comment]
@rinatkhaziev please take a look :-)

**Comment by rinatkhaziev** [comment]
@sjinks I tested the basic scenarios and it seems to work fine!

**Pull request merged**
